= Cassandra data performance data collection

This repository contains the configuration to use link:http://www.opennms.org[OpenNMS] collecting performance metrics provided through JMX for a Cassandra node.

== Requirements

* Tested with Cassandra 3.11
* OpenNMS Horizon/Meridian
* Java JMX access to the Cassandra node
* Provision your Cassandra nodes into OpenNMS for monitoring
* The config example has OpenNMS installed in `/opt/opennms`, on Debian/Ubuntu change the path accordingly to `/usr/share/opennms`

== Install data collection configuration

Checkout this repository with git or copy the files manually using the GitHub raw link to download the configuration files.

.Install configuration for metrics collection and RRD graph definitions
[source, bash]
----
git clone https://github.com/opennms-config-modules/cassandra.git
cd cassandra
cp graphs/cassandra-3x-graph.properties /opt/opennms/etc/snmp-graph.properties.d
cp datacollection/cassandra-3x.xml /opt/opennms/etc/jmx-datacollection-config.d
----

== Configure Collectd

Add the following lines `collectd-configuration.xml` in the `in the default installed ``example1` package.

.Create a new collection service for the Cassandra metrics
[source, xml]
----
<service name="JMX-Cassandra" interval="30000" user-defined="false" status="on">
    <parameter key="port" value="7199"/>
    <parameter key="retry" value="2"/>
    <parameter key="timeout" value="3000"/>
    <parameter key="rrd-base-name" value="jmx-cassandra"/>
    <parameter key="collection" value="jmx-cassandra3x"/>
    <parameter key="thresholding-enabled" value="true"/>
    <parameter key="ds-name" value="jmx-cassandra"/>
    <parameter key="friendly-name" value="jmx-cassandra"/>
    <parameter key="protocol" value="rmi"/>
    <parameter key="urlPath" value="/jmxrmi"/>
    <parameter key="factory" value="PASSWORD-CLEAR"/>
    <parameter key="username" value="cassandra"/>
    <parameter key="password" value="cassandra"/>
</service>

<collector service="JMX-Cassandra" class-name="org.opennms.netmgt.collectd.Jsr160Collector"/>
----

Restart OpenNMS and provision a service on your nodes IP interface named `JMX-Cassandra`.

== Author
ronny@opennms.org
